import Foundation

struct Question {
    let id: String
    let text: String
    let category: String
}

extension Question {
    static let sampleQuestions: [String: [Question]] = [
        "LES PLUS HOTS": lessPlusHotsQuestions
    ]
    
    private static let lessPlusHotsQuestions: [Question] = [
        // Questions 1-50
        Question(id: "lph-1", text: "Quel désir secret aimerais-tu explorer avec moi, tout en confiance ?", category: "LES PLUS HOTS"),
        Question(id: "lph-2", text: "Quel compliment chuchoté pourrait te faire frissonner instantanément ?", category: "LES PLUS HOTS"),
        Question(id: "lph-3", text: "Quelle expérience inattendue t'intrigue dans notre intimité ?", category: "LES PLUS HOTS"),
        Question(id: "lph-4", text: "As-tu déjà imaginé un moment sensuel entre nous ? Comment serait-il ?", category: "LES PLUS HOTS"),
        Question(id: "lph-5", text: "Y a-t-il une mise en scène ou un jeu que tu aimerais vivre ensemble ?", category: "LES PLUS HOTS"),
        Question(id: "lph-6", text: "Quelle question n'oses-tu pas me poser à propos de notre complicité physique ?", category: "LES PLUS HOTS"),
        Question(id: "lph-7", text: "Quelle douceur rêverais-tu que je t'offre dans un moment intime ?", category: "LES PLUS HOTS"),
        Question(id: "lph-8", text: "As-tu déjà imaginé un baiser volé entre nous dans un endroit improbable ?", category: "LES PLUS HOTS"),
        Question(id: "lph-9", text: "Qu'est-ce qui te fait le plus envie quand tu penses à moi en ce moment ?", category: "LES PLUS HOTS"),
        Question(id: "lph-10", text: "Quelle tenue ou style te rend particulièrement réceptif(ve) à l'envie ?", category: "LES PLUS HOTS"),
        Question(id: "lph-11", text: "Quel est ton endroit préféré pour recevoir un baiser ?", category: "LES PLUS HOTS"),
        Question(id: "lph-12", text: "Quelle ambiance te met tout de suite dans un état sensuel ?", category: "LES PLUS HOTS"),
        Question(id: "lph-13", text: "Quelle est la chose la plus tendre qui t'excite réellement ?", category: "LES PLUS HOTS"),
        Question(id: "lph-14", text: "As-tu une chanson qui te donne envie de moments intimes ?", category: "LES PLUS HOTS"),
        Question(id: "lph-15", text: "Quelle partie de ton corps devrais-je explorer plus souvent selon toi ?", category: "LES PLUS HOTS"),
        Question(id: "lph-16", text: "Quel type de massage t'excite sans forcément en avoir l'air ?", category: "LES PLUS HOTS"),
        Question(id: "lph-17", text: "Quel fantasme doux ou mystérieux aimerais-tu qu'on réalise ensemble ?", category: "LES PLUS HOTS"),
        Question(id: "lph-18", text: "Quel est ton souvenir sensuel préféré avec moi ?", category: "LES PLUS HOTS"),
        Question(id: "lph-19", text: "Quelle est la chose la plus simple que je puisse faire qui te donne des frissons ?", category: "LES PLUS HOTS"),
        Question(id: "lph-20", text: "As-tu un endroit où tu rêverais qu'on se retrouve seuls tous les deux ?", category: "LES PLUS HOTS"),
        Question(id: "lph-21", text: "Quelle caresse t'apaise mais t'éveille en même temps ?", category: "LES PLUS HOTS"),
        Question(id: "lph-22", text: "Y a-t-il un mot ou une phrase qui t'allume quand je le dis ?", category: "LES PLUS HOTS"),
        Question(id: "lph-23", text: "Quel regard ou attitude chez moi te fait perdre le fil ?", category: "LES PLUS HOTS"),
        Question(id: "lph-24", text: "Quelle est l'idée la plus douce et audacieuse que tu as eue en pensant à nous ?", category: "LES PLUS HOTS"),
        Question(id: "lph-25", text: "Quelle sensation adores-tu ressentir sur ta peau ?", category: "LES PLUS HOTS"),
        Question(id: "lph-26", text: "Qu'est-ce que tu trouves le plus séduisant dans mes gestes ?", category: "LES PLUS HOTS"),
        Question(id: "lph-27", text: "Quelle scène romantique ou sensuelle d'un film t'a donné envie de la vivre ?", category: "LES PLUS HOTS"),
        Question(id: "lph-28", text: "Quel est le moment de la journée où tu te sens le plus en éveil ?", category: "LES PLUS HOTS"),
        Question(id: "lph-29", text: "Quelle matière ou tissu te donne des frissons ?", category: "LES PLUS HOTS"),
        Question(id: "lph-30", text: "Quelle est ta définition d'une étreinte parfaite ?", category: "LES PLUS HOTS"),
        Question(id: "lph-31", text: "Qu'aimerais-tu que je te murmure dans un moment intime ?", category: "LES PLUS HOTS"),
        Question(id: "lph-32", text: "Si je devais te surprendre en douceur, comment devrais-je m'y prendre ?", category: "LES PLUS HOTS"),
        Question(id: "lph-33", text: "Quelle pensée coquine t'arrive quand tu penses à moi ?", category: "LES PLUS HOTS"),
        Question(id: "lph-34", text: "Quel geste subtil te fait le plus d'effet dans l'intimité ?", category: "LES PLUS HOTS"),
        Question(id: "lph-35", text: "Y a-t-il un parfum ou une odeur qui te réveille le désir ?", category: "LES PLUS HOTS"),
        Question(id: "lph-36", text: "Quelle est ta manière favorite de me montrer ton envie ?", category: "LES PLUS HOTS"),
        Question(id: "lph-37", text: "Quelle caresse t'a marqué(e) et que tu aimerais revivre ?", category: "LES PLUS HOTS"),
        Question(id: "lph-38", text: "Quel est le moment inattendu où tu as ressenti du désir pour moi ?", category: "LES PLUS HOTS"),
        Question(id: "lph-39", text: "As-tu déjà eu une envie forte en pleine journée, sans raison apparente ?", category: "LES PLUS HOTS"),
        Question(id: "lph-40", text: "Si je t'invitais à un jeu de séduction, que proposerais-tu ?", category: "LES PLUS HOTS"),
        Question(id: "lph-41", text: "Qu'est-ce que je fais sans m'en rendre compte qui t'attire physiquement ?", category: "LES PLUS HOTS"),
        Question(id: "lph-42", text: "Quel est ton plus grand désir non exprimé dans notre intimité ?", category: "LES PLUS HOTS"),
        Question(id: "lph-43", text: "Y a-t-il un moment intime que tu aimerais revisiter différemment ?", category: "LES PLUS HOTS"),
        Question(id: "lph-44", text: "Quelle est ta manière préférée de recevoir de l'attention dans un moment charnel ?", category: "LES PLUS HOTS"),
        Question(id: "lph-45", text: "Quel regard ou sourire te fait fondre quand on est proches ?", category: "LES PLUS HOTS"),
        Question(id: "lph-46", text: "Y a-t-il un lieu que tu trouves particulièrement excitant rien qu'en y pensant ?", category: "LES PLUS HOTS"),
        Question(id: "lph-47", text: "Qu'aimerais-tu que je fasse plus lentement pour prolonger le plaisir ?", category: "LES PLUS HOTS"),
        Question(id: "lph-48", text: "Quelle émotion précède souvent ton envie de moi ?", category: "LES PLUS HOTS"),
        Question(id: "lph-49", text: "Quelle tenue t'imagines-tu porter pour me surprendre agréablement ?", category: "LES PLUS HOTS"),
        Question(id: "lph-50", text: "As-tu une idée de surprise romantique et sensuelle que tu aimerais organiser ?", category: "LES PLUS HOTS"),
        
        // Questions 51-100
        Question(id: "lph-51", text: "Si tu pouvais inventer une soirée dédiée au plaisir doux, à quoi ressemblerait-elle ?", category: "LES PLUS HOTS"),
        Question(id: "lph-52", text: "Quelle est la chose la plus subtile qui t'a fait frissonner récemment ?", category: "LES PLUS HOTS"),
        Question(id: "lph-53", text: "As-tu un rêve éveillé récurrent qui te relie à moi de manière sensuelle ?", category: "LES PLUS HOTS"),
        Question(id: "lph-54", text: "Quel mot te fait rougir rien qu'en l'entendant dans ma bouche ?", category: "LES PLUS HOTS"),
        Question(id: "lph-55", text: "Quel geste tendre t'a déjà fait monter le désir très vite ?", category: "LES PLUS HOTS"),
        Question(id: "lph-56", text: "Quelles sont les choses que tu voudrais que je découvre encore sur ton corps ?", category: "LES PLUS HOTS"),
        Question(id: "lph-57", text: "Quelle partie de moi observes-tu avec désir sans le dire ?", category: "LES PLUS HOTS"),
        Question(id: "lph-58", text: "Quel est le moment de notre intimité où tu t'es senti(e) le plus désiré(e) ?", category: "LES PLUS HOTS"),
        Question(id: "lph-59", text: "Quelle est la chose la plus romantique qui t'excite plus qu'on ne pourrait croire ?", category: "LES PLUS HOTS"),
        Question(id: "lph-60", text: "Qu'est-ce qui te donne le sentiment d'un abandon total entre mes bras ?", category: "LES PLUS HOTS"),
        Question(id: "lph-61", text: "Quelle est ta façon secrète de me dire que tu as envie sans le dire vraiment ?", category: "LES PLUS HOTS"),
        Question(id: "lph-62", text: "Quand tu penses à nous dans un moment intime, quel est le détail qui revient ?", category: "LES PLUS HOTS"),
        Question(id: "lph-63", text: "Quelle émotion te connecte au plaisir plus qu'aucune autre ?", category: "LES PLUS HOTS"),
        Question(id: "lph-64", text: "Si on pouvait se téléporter dans un lieu pour un moment intime, où irait-on ?", category: "LES PLUS HOTS"),
        Question(id: "lph-65", text: "Qu'aimerais-tu que je te chuchote quand tu te sens vulnérable et ouvert(e) ?", category: "LES PLUS HOTS"),
        Question(id: "lph-66", text: "Quel est ton souvenir le plus électrique d'un baiser échangé entre nous ?", category: "LES PLUS HOTS"),
        Question(id: "lph-67", text: "Y a-t-il un moment où tu t'es surpris(e) à désirer quelque chose de nouveau avec moi ?", category: "LES PLUS HOTS"),
        Question(id: "lph-68", text: "Quelle lumière ou ambiance t'éveille sensuellement ?", category: "LES PLUS HOTS"),
        Question(id: "lph-69", text: "Quelle tendresse précède le désir chez toi ?", category: "LES PLUS HOTS"),
        Question(id: "lph-70", text: "Quel moment passé avec moi t'a laissé un frisson dans le dos ?", category: "LES PLUS HOTS"),
        Question(id: "lph-71", text: "Quelle situation banale t'a déjà donné une envie inattendue ?", category: "LES PLUS HOTS"),
        Question(id: "lph-72", text: "Quelle est ta plus grande surprise sensuelle que tu as vécue avec moi ?", category: "LES PLUS HOTS"),
        Question(id: "lph-73", text: "Quelle douceur te fait le plus de bien avant un moment plus intime ?", category: "LES PLUS HOTS"),
        Question(id: "lph-74", text: "Si je devais te séduire sans un mot, qu'attendrais-tu de moi ?", category: "LES PLUS HOTS"),
        Question(id: "lph-75", text: "Qu'aimerais-tu tenter dans notre intimité tout en douceur et en confiance ?", category: "LES PLUS HOTS"),
        Question(id: "lph-76", text: "Y a-t-il une pensée que tu gardes en secret et qui te fait sourire de désir ?", category: "LES PLUS HOTS"),
        Question(id: "lph-77", text: "Quelle est ta zone la plus réceptive au contact léger ?", category: "LES PLUS HOTS"),
        Question(id: "lph-78", text: "Si on créait ensemble un moment parfait pour se reconnecter physiquement, que ferais-tu ?", category: "LES PLUS HOTS"),
        Question(id: "lph-79", text: "Quand te sens-tu le plus irrésistible à mes yeux ?", category: "LES PLUS HOTS"),
        Question(id: "lph-80", text: "Quel est le moment exact où tu ressens un frisson rien qu'à ma proximité ?", category: "LES PLUS HOTS"),
        Question(id: "lph-81", text: "Quelle est la chose la plus inattendue que tu trouves sensuelle chez moi ?", category: "LES PLUS HOTS"),
        Question(id: "lph-82", text: "Quelle invitation discrète pourrais-tu me faire pour éveiller notre complicité charnelle ?", category: "LES PLUS HOTS"),
        Question(id: "lph-83", text: "Si je devais t'emmener dans un univers de sensualité, que voudrais-tu y trouver ?", category: "LES PLUS HOTS"),
        Question(id: "lph-84", text: "Qu'est-ce que tu adorerais qu'on redécouvre ensemble, même si on l'a déjà vécu ?", category: "LES PLUS HOTS"),
        Question(id: "lph-85", text: "Quand sens-tu que notre désir devient émotion ?", category: "LES PLUS HOTS"),
        Question(id: "lph-86", text: "Qu'aimerais-tu que je fasse quand je sens ton envie sans que tu aies à parler ?", category: "LES PLUS HOTS"),
        Question(id: "lph-87", text: "Y a-t-il une sensation oubliée que tu voudrais revivre avec moi ?", category: "LES PLUS HOTS"),
        Question(id: "lph-88", text: "Qu'est-ce qui chez moi réveille ton côté joueur(se) ?", category: "LES PLUS HOTS"),
        Question(id: "lph-89", text: "Si tu pouvais revivre un moment charnel avec moi, lequel choisirais-tu ?", category: "LES PLUS HOTS"),
        Question(id: "lph-90", text: "Quelle est ta façon préférée d'initier un moment intime ?", category: "LES PLUS HOTS"),
        Question(id: "lph-91", text: "Qu'est-ce que tu aimerais que je t'apprenne sur le plaisir mutuel ?", category: "LES PLUS HOTS"),
        Question(id: "lph-92", text: "Quelle est ta plus belle surprise intime dans notre relation jusqu'à maintenant ?", category: "LES PLUS HOTS"),
        Question(id: "lph-93", text: "Si je te demandais de me guider, où m'emmènerais-tu sur ton corps ?", category: "LES PLUS HOTS"),
        Question(id: "lph-94", text: "Qu'est-ce qui te donne envie de me garder près de toi toute la nuit ?", category: "LES PLUS HOTS"),
        Question(id: "lph-95", text: "Quel geste tendre t'excite plus qu'il ne devrait ?", category: "LES PLUS HOTS"),
        Question(id: "lph-96", text: "Quand as-tu ressenti une tension douce et agréable rien qu'en me regardant ?", category: "LES PLUS HOTS"),
        Question(id: "lph-97", text: "Quelle phrase douce t'a déjà plongé dans une bulle de désir ?", category: "LES PLUS HOTS"),
        Question(id: "lph-98", text: "Qu'aimerais-tu que je fasse pour éveiller tes sens un soir de pleine lune ?", category: "LES PLUS HOTS"),
        Question(id: "lph-99", text: "Si on écrivait ensemble une scène romantique et intense, que contiendrait-elle ?", category: "LES PLUS HOTS"),
        Question(id: "lph-100", text: "Quelle intention douce me conseillerais-tu d'avoir pour éveiller ton désir ce soir ?", category: "LES PLUS HOTS")
    ]
} 